app/models.py
from . import db, login_manager
from flask_login import UserMixin
from werkzeug.security import generate_password_hash,check_password_hash

@login_manager.user_loader
def load_user(user_id):
    return User.query.get(int(user_id))

class User(UserMixin,db.Model):
    __tablename__ = 'users'
    id = db.Column(db.Integer,primary_key = True)
    username = db.Column(db.String(255))
    email = db.Column(db.String(255))
    pass_secure  = db.Column(db.String(255))

    @property
    def password(self):
        raise AttributeError('You cannot read the password attribute')

    @password.setter
    def password(self, password):
        self.pass_secure = generate_password_hash(password)


    def verify_password(self,password):
        return check_password_hash(self.pass_secure,password)

    def __repr__(self):
        return f'User {self.username}'
    
class Subscribers(db.Model):
    __tablename__='subscribers'
    id = db.Column(db.Integer,primary_key = True)
    email = db.Column(db.String(255))

    def save_subscriber(self):
        db.session.add(self)
        db.session.commit()

    @classmethod
    def get_subscribers(cls):
        subscribers=Subscribers.query.all()
        return subscribers

    def __repr__(self):
        return f'Subscribers {self.email}'

class BlogPost(db.Model):
    __tablename__='blogs'
    id = db.Column(db.Integer,primary_key = True)
    title = db.Column(db.String())
    blog_post = db.Column(db.String)
    blog_pic = db.Column(db.String)
    photo_url = db.Column(db.String)

    comment = db.relationship('Comment',backref='blog',lazy='dynamic')
    user_id = db.Column(db.Integer, db.ForeignKey('users.id'))

    def save_blog(self):
       db.session.add(self)
       db.session.commit()

    
    @classmethod
    def get_blog(cls,id):
        blog = BlogPost.query.filter_by(id = id).first()
        return blog
    
    @classmethod
    def get_all_blogs(cls):
        blogs = BlogPost.query.order_by('-id').all()
        return blogs

class Comment(db.Model):
    __tablename__='comments'
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String())
    comment_content = db.Column(db.String())

    blog_id = db.Column(db.Integer, db.ForeignKey('blogs.id'))
    user_id = db.Column(db.Integer, db.ForeignKey('users.id'))
    
    def save_comment(self):
        db.session.add(self)
        db.session.commit()

    @classmethod
    def get_single_comment(cls,id_blog,id):
        comment = Comment.query.filter_by(blog_id=id_blog,id=id).first()
        return comment
    
    @classmethod
    def get_all_comments(cls,id):
        comments = Comment.query.filter_by(blog_id=id).order_by('-id').all()
        return comments
    
    

app/main/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, TextAreaField
from wtforms.validators import Required, DataRequired, Length

class SubscriberForm(FlaskForm):
    email = StringField('Email', validators=[Required()])
    subscribe = SubmitField('Subscribe')

class BlogPostForm(FlaskForm):
    title = StringField('Title', validators=[DataRequired(),Length(min=1, max=1000)])
    photo_url = StringField('Photo URL', validators=[Required()])
    blog_content= TextAreaField('Post your blog', validators=[DataRequired(), Length(min=1)])
    submit = SubmitField('Submit')

class CommentForm(FlaskForm):
    name = StringField('Name',validators=[Required()])
    comment_content = TextAreaField('Enter Comment', validators=[Required()])
    submit = SubmitField('submit Comment')

app/__init__.py
from flask import Flask
from flask_bootstrap import Bootstrap
from config import config_options
from flask_sqlalchemy import SQLAlchemy
from flask_mail import Mail
from flask_login import LoginManager

login_manager = LoginManager()
login_manager.session_protection = 'strong'
login_manager.login_view = 'auth.login'

bootstrap = Bootstrap()
db = SQLAlchemy()
mail = Mail()

def create_app(config_name):
    app = Flask(__name__)

    # Creating the app configurations
    app.config.from_object(config_options[config_name])

    # Initializing flask extensions
    bootstrap.init_app(app)
    db.init_app(app)
    mail.init_app(app)
    login_manager.init_app(app)

    # Registering the blueprint
    from .main import main as main_blueprint
    app.register_blueprint(main_blueprint)

    from .auth import auth as auth_blueprint
    app.register_blueprint(auth_blueprint,url_prefix = '/authenticate')


    return app

app/main/__init__.py
from flask import Blueprint
main = Blueprint('main',__name__)
from . import views,errors

app/main/views.py
from flask import render_template, redirect, url_for,flash, abort
from . import main
from .forms import SubscriberForm, BlogPostForm, CommentForm
from ..models import User, Subscribers, BlogPost, Comment
from ..email import mail_message
from .. import db
from flask_login import login_required, current_user

@main.route('/',methods=['GET', 'POST'])
def index():

    '''
    View root page function that returns the index page and its data
    '''
    title= "Personal Blog"

    subscribers = SubscriberForm()
    if subscribers.validate_on_submit():
        subscriber = Subscribers(email = subscribers.email.data)
        db.session.add(subscriber)
        db.session.commit()
        flash('You are now subscribed')
        mail_message("Welcome to my blog","email/welcome",subscriber.email,subscriber=subscriber)
        return redirect(url_for('main.index'))

    all_blogs = BlogPost.get_all_blogs()
    if all_blogs:
        blogs= all_blogs
        return render_template('index.html',title=title, all_blogs= blogs, subscribers=subscribers)
    elif not all_blogs:
        blog_status= 'There are no blogs'
        return render_template('index.html', title=title, blog_status=blog_status,subscribers=subscribers)

@main.route('/create_blogpost', methods = ['GET', 'POST'])
@login_required
def create_blogpost():
    title="Create BlogPost"

    blog_form = BlogPostForm()

    if blog_form.validate_on_submit():
        blog = BlogPost(title= blog_form.title.data, blog_post= blog_form.blog_content.data)
        db.session.add(blog)
        db.session.commit()
        return redirect(url_for('main.create_blogpost'))

    comment_form = CommentForm()
    if comment_form.validate_on_submit():
        new_comment = Comment(name= comment_form.name.data, comment_content= comment_form.comment_content.data)
        db.session.add(new_comment)
        db.session.commit()
        return redirect(url_for('main.create_blogpost'))


    return render_template('blog.html', BlogPost = blog_form, title=title, comment_form=comment_form)

@main.route('/blogpost/<id>', methods=['POST','GET'])
def blogpost(id):
    
    title= f'Posts' 
    blog = BlogPost.query.filter_by(id=id).first()
    comment_form = CommentForm()
    if comment_form.validate_on_submit():
        new_comment = Comment(name= comment_form.name.data,comment_content = comment_form.comment_content.data, blog_id=id)
        db.session.add(new_comment)
        db.session.commit()
        return redirect(url_for('main.blogpost',id=blog.id))

    all_comments = Comment.query.all()
    blog_comments = Comment.query.filter_by(blog_id=id).all()

    return render_template('blogpost.html', title = title, blog=blog, comment_form=comment_form,all_comments=all_comments,blog_comments=blog_comments)

@main.route('/blog/<int:id>/<int:id_comment>/delete_comment')
@login_required
def delete_comment(id,id_comment):
    comment = Comment.get_single_comment(id,id_comment)

    db.session.delete(comment)
    db.session.commit()

    flash('Comment has been deleted')

    return redirect(url_for('main.blogpost',id=id))

@main.route('/index/<int:id>/delete_blog')
@login_required
def delete_blog(id):
    blog = BlogPost.get_blog(id)

    db.session.delete(blog)
    db.session.commit()

    flash('Blog has been deleted') 

    return redirect(url_for('main.index', id=id))

app/templates/base.html
{% extends 'bootstrap/base.html' %}

{% block styles %}
{{ super() }}

{% endblock %}

{% block navbar%}
{% include 'navbar.html' %}
{% endblock %}

app/templates/blog.html
{% extends 'base.html' %} 
{% import 'bootstrap/wtf.html' as wtf %} 

{% block content %}
<div class="container">
  <div class="row">
    <div class="col-xs-10 col-xs-offset-1">
      {{wtf.quick_form(BlogPost)}}
      <button>
        <a href="{{url_for('main.index')}}">See all blogs</a>
      </button>
    </div>
  </div>
</div>
{% endblock %}

app/templates/blogpost.html
{% extends 'base.html' %}
{% block content %}
<head>
    <style>
        body {
              background-color: whitesmoke;
          }
    </style>
</head>
<body>
<div class="container">
    <div class="row">
        <div class="col-xs-10 col-xs-offset-1">
            <h1>TITLE: {{blog.title}}</h1>
            <hr>
            <br>
            <p>{{blog.blog_post}}</p>
            <hr>
            {% if current_user.is_authenticated%}
            <button class="btn btn-danger"><a href="{{url_for('main.delete_blog',id=blog.id)}}">Delete Blog</a></button>
            {% endif %}
        </div>
    </div>
</div>

<div class="container">
    <div class="row">
        <div class-"col-md-3"></div>
        <div class="col-md-6">
            {% import 'bootstrap/wtf.html' as wtf %}
            {{wtf.quick_form(comment_form)}}
            <br>
            <h3>COMMENTS</h3>
            <hr>
        </div>
        <div class-"col-md-3"></div>
        </div>
        {% for one_comment in blog_comments %}
        <div class="row">       
            <div class="col-md-6">
            <p>{{one_comment.name}} says: {{one_comment.comment_content}}</p>
            </div>
            <div class="col-md-3">
            {% if current_user.is_authenticated%}
            <button class="btn btn-danger"><a href="{{url_for('main.delete_comment',id=one_comment.blog_id,id_comment=one_comment.id)}}">Delete Comment</a></button>
            {% endif %}
            </div>
            <div class="col-md-3"></div>
             <hr>
        </div>
        {% endfor %}
        </div>
        </body>
{% endblock %}

app/templates/create_blog.html
{% extends 'base.html' %} 

    <body>
        <div class="container-fluid">
            <div class="row">
            <div class="col-md-1"> </div>
            <div class="col-md-10">
                    <legend class="border-bottom mb-4" style="font-size:25px;">Create Blog</legend>
                    <form action="" method="post">
                            {{blog_form.hidden_tag()}}
                            <p>{{blog_form.title.label}}</p>
                            <p>{{blog_form.title}}</p>
                            {% for error in blog_form.title.errors %}
                                <span style="color: red;">[{{ error }}]</span>
                            {% endfor %}
    
                            <p>{{blog_form.photo_url.label}}</p>
                            <p>{{blog_form.photo_url}}</p>
                            {% for error in blog_form.photo_url.errors %}
                                <span style="color: red;">[{{ error }}]</span>
                            {% endfor %}
    
                            <p>{{blog_form.blog_content.label}}</p>
                            <p>{{blog_form.blog_content}}</p>
                            {% for error in blog_form.blog_content.errors %}
                                <span style="color: red;">[{{ error }}]</span>
                            {% endfor %}
    
                            <p>{{blog_form.submit()}}</p>
                        </form>
                    
    
            </div>
            <div class="col-md-1"></div>
            </div>
    </div>
    </body>

app/templates/index.html
{% extends 'base.html' %}
{% import 'bootstrap/wtf.html' as wtf %}

{% block content %}

  <head>
      <style>
          body {
              background-color: whitesmoke;
          }
          .blogs {
              background-color: ivory;
              box-sizing: border-box;
              border: 2px solid grey;
              margin-left: 25px;
              margin-top: 15px;
          }
          .heading {
              font-size: 45px;
              margin-left: 250px;
              font-style:italic;
              text-decoration: underline;
          }
      </style>
  </head>
  <body>
        <div class="container-fluid">
                <div class="row">
                <div class="col-md-6">
                        <legend class="border-bottom mb-4" style="font-size:25px;">Subscribe To Our Blogs</legend>
                        {{wtf.quick_form(subscribers)}}
                </div>
                <div class="col-md-2"></div>
                <div class="col-md-4"></div>
               
                </div>
                </div>


        <div class="container">

               <h1 class="heading">HERE ARE YOUR BLOGS</h1>
                <div class="row">
                    <div class="col-md-2"></div>
                    
                    {% for blog in all_blogs %}
                    <div class="col-md-8 blogs">
                            {% if blog.photo_url %}
                           
                            <a href="{{url_for('main.blogpost',id=blog.id)}}">
                                <img src="{{blog.photo_url}}" alt="Loading Image" class="img-responsive">
                            </a>
                            {% else %}
                            <a href="{{url_for('main.blogpost',id=blog.id)}}">
                                <img src="{{url_for('static',filename='')}}" alt="blog-image" class="img-responsive">
                            </a>
                            {% endif %}
                                <h3><a href="{{url_for('main.blogpost',id=blog.id)}}">{{blog.title}}</a></h3>
                                <hr>
                                <p> {{blog.blog_content}}<a href="{{url_for('main.blogpost',id=blog.id)}}">View More</a></p>
                               
                            </div>   
                    {% endfor %}
                
                    <div class="col-md-2"></div>
                </div> 
                   
                </div>
            </div>
            </body>

{% endblock %}

app/templates/navbar.html
<head>
    <style>
        .navbar {
          background-color: silver;
        }
    </style>
</head>
<body>
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="{{url_for('main.index')}}">PERSONAL BLOG</a>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="nav navbar-nav navbar-right">
                <li><a href="{{url_for('main.index')}}">HOME</a></li>
                {% if current_user.is_authenticated %}
                <li><a href="{{url_for('main.create_blogpost')}}">Create Blog</a></li>
                <li style="color:white;padding:15px;">{{current_user.username}}</li>
                <li><a href="{{url_for('auth.logout')}}">Sign out</a></li>
                {% else %}
                <li><a href="{{url_for('auth.register')}}">Register</a></li>
                <li class="divider"></li>
                <li><a href="{{url_for('auth.login')}}">Sign in</a></li>
                <li class="divider"></li>
                {%endif%}
        </ul>
      </ul>
</nav>
</body>